const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');
const path = require('path');

const START_YEAR = 1980;
const END_YEAR = new Date().getFullYear();

function cleanText(text) {
  if (!text) return '';
  return text.replace(/\(Live\)/gi, '')
             .replace(/\(Inst\.\)/gi, '')
             .replace(/\(MR\)/gi, '')
             .replace(/\(Special Edition\)/gi, '')
             .replace(/\s+/g, ' ')
             .trim();
}

async function runFastScraper() {
  console.log('🚀 ( 초고속 파이프라인 매크로 ) 지니뮤직 1980~2026 월간 차트 TOP 100 수집 시작!');
  
  const allSongs = [];
  
  for (let year = END_YEAR; year >= START_YEAR; year--) {
    const startMonth = (year === END_YEAR) ? (new Date().getMonth() + 1) : 12;
    
    for (let month = startMonth; month >= 1; month--) {
      const monthStr = month.toString().padStart(2, '0');
      let monthCount = 0;
      
      for (let pg = 1; pg <= 2; pg++) {
        const url = `https://www.genie.co.kr/chart/musicHistory?year=${year}&category=0&month=${month}&pg=${pg}`;
        try {
          const res = await axios.get(url, {
            headers: {
              'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            },
            timeout: 10000
          });
          
          const $ = cheerio.load(res.data);
          const rows = $('tr.list');
          
          rows.each((idx, el) => {
            const titleEl = $(el).find('a.title.ellipsis');
            const artistEl = $(el).find('a.artist.ellipsis');
            if (titleEl.length && artistEl.length) {
              const title = cleanText(titleEl.text().trim());
              const artist = cleanText(artistEl.text().trim());
              const rank = (pg - 1) * 50 + idx + 1;
              
              let genre = '발라드';
              let gender = '혼성';

              if (artist.match(/아이유|aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|이효리|백지영|보아|태연|에일리|레드벨벳/i)) gender = '여성';
              else if (artist.match(/BTS|방탄소년단|세븐틴|EXO|BIGBANG|임영웅|조용필|성시경|박효신|SG워너비|god|신승훈|김건모/i)) gender = '남성';

              if (artist.match(/aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|BTS|EXO|BIGBANG|H.O.T.|젝스키스|핑클|S.E.S.|코요태/i)) genre = '댄스';
              else if (artist.match(/임영웅|영탁|장윤정|송가인|주현미|김수희/i)) genre = '트로트';
              else if (artist.match(/버즈|DAY6|윤도현|잔나비|자우림|혁오|국카스텐/i)) genre = '록/밴드';
              else if (artist.match(/다이나믹 듀오|에픽하이|지코|비와이/i)) genre = '힙합';

              allSongs.push({ year, month, rank, title, artist, genre, gender });
              monthCount++;
            }
          });
        } catch (e) {
          // ignore single page errors
        }
      }
      if (monthCount > 0) {
        console.log(`✅ ${year}년 ${monthStr}월: ${monthCount}곡 수집 (누적: ${allSongs.length}개 차트 데이터)`);
      }
    }
  }
  
  console.log(`\n🎉 수집 완료! 총 ${allSongs.length}개 차트 데이터 저장 중...`);
  const fileContent = `// TJ Karaoke Genie Scraped Monthly TOP 100 Database (1980-2026)
// Total Entries: ${allSongs.length}
// Auto-generated by fast_genie_monthly.js

const SONG_DATABASE = ${JSON.stringify(allSongs, null, 2)};
if (typeof module !== 'undefined') module.exports = SONG_DATABASE;
`;
  
  fs.writeFileSync(path.join(__dirname, 'songData.js'), fileContent, 'utf8');
  console.log('💾 songData.js 저장 완료!');
}

runFastScraper();
