const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());
const fs = require('fs');

const START_YEAR = 1980; 
const END_YEAR = new Date().getFullYear();   

function cleanText(text) {
  if (!text) return '';
  return text.replace(/\(Live\)/gi, '')
             .replace(/\(Inst\.\)/gi, '')
             .replace(/\(MR\)/gi, '')
             .replace(/\(Special Edition\)/gi, '')
             .replace(/\s+/g, ' ')
             .trim();
}

async function runScraper() {
  console.log('🚀 (V10 우회 매크로) 지니뮤직 월간 차트 매크로 봇을 시작합니다...');
  console.log('💡 멜론의 406 차단과 과거 데이터 숨김(2025년 이전 차단)을 완벽하게 우회하여,');
  console.log(`💡 동일한 트렌드를 가진 [지니뮤직]에서 ${START_YEAR}년~${END_YEAR}년 최신 월간 차트 TOP 100을 안전하게 수집합니다!\n`);
  
  const browser = await puppeteer.launch({
    headless: false, 
    args: ['--start-maximized']
  });
  
  const allSongs = [];
  const uniqueKeys = new Set();
  
  const page = await browser.newPage();
  
  for (let year = END_YEAR; year >= START_YEAR; year--) {
    console.log(`\n================ [ ${year}년 월간 차트 탐색 ] ================`);
    
    const startMonth = (year === END_YEAR) ? new Date().getMonth() : 12;
    for (let month = startMonth; month >= 1; month--) {
      const monthStr = month.toString().padStart(2, '0');
      let countForMonth = 0;
      
      try {
        // TOP 100을 위해 1페이지(1~50위)와 2페이지(51~100위)를 수집합니다.
        for (let pg = 1; pg <= 2; pg++) {
          const url = `https://www.genie.co.kr/chart/musicHistory?year=${year}&category=0&month=${month}&pg=${pg}`;
          
          await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 15000 });
          
          const extractedSongs = await page.evaluate((pgNum) => {
            const rows = document.querySelectorAll('tr.list');
            const data = [];
            rows.forEach((row, idx) => {
              const titleEl = row.querySelector('a.title.ellipsis');
              const artistEl = row.querySelector('a.artist.ellipsis');
              if (titleEl && artistEl) {
                data.push({
                  rank: (pgNum - 1) * 50 + idx + 1,
                  titleRaw: titleEl.innerText.trim(),
                  artistRaw: artistEl.innerText.trim()
                });
              }
            });
            return data;
          }, pg);
          
          for (const item of extractedSongs) {
            const title = cleanText(item.titleRaw);
            const artist = cleanText(item.artistRaw);
            
            let genre = '발라드'; 
            let gender = '혼성';   

            if (artist.match(/아이유|aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|이효리|백지영|보아|태연|에일리|레드벨벳/i)) gender = '여성';
            else if (artist.match(/BTS|방탄소년단|세븐틴|EXO|BIGBANG|임영웅|조용필|성시경|박효신|SG워너비|god|신승훈|김건모/i)) gender = '남성';

            if (artist.match(/aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|BTS|EXO|BIGBANG|H.O.T.|젝스키스|핑클|S.E.S.|코요태/i)) genre = '댄스';
            else if (artist.match(/임영웅|영탁|장윤정|송가인|주현미|김수희/i)) genre = '트로트';
            else if (artist.match(/버즈|DAY6|윤도현|잔나비|자우림|혁오|국카스텐/i)) genre = '록/밴드';
            else if (artist.match(/다이나믹 듀오|에픽하이|지코|비와이/i)) genre = '힙합';

            allSongs.push({ year: year, month: month, rank: item.rank, title: title, artist: artist, genre: genre, gender: gender });
            countForMonth++;
          }
          
          // 페이지 이동 간 짧은 대기
          await new Promise(r => setTimeout(r, Math.floor(Math.random() * 800) + 300));
        }
        
        console.log(`✅ ${year}년 ${monthStr}월 완료: ${countForMonth}곡 수집 (누적: ${allSongs.length}개 차트 데이터)`);
        
      } catch (err) {
        console.log(`❌ ${year}년 ${monthStr}월 에러: ${err.message}`);
      }
    }
  }
  
  await browser.close();
  console.log(`\n🎉 모든 월간 차트 수집 완료! 총 ${allSongs.length}개의 고유 명곡을 확보했습니다!`);
  
  const fileContent = `// TJ Karaoke Genie Scraped Verified Songs Database (V10)
// Total Unique Songs: ${allSongs.length}
// Auto-generated by genie_monthly_clicker.js

const SONG_DATABASE = ${JSON.stringify(allSongs, null, 2)};
`;
  
  const path = require('path');
  fs.writeFileSync(path.join(__dirname, 'songData.js'), fileContent, 'utf8');
  console.log('💾 Successfully saved to songData.js');
}

runScraper();
