const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');

const START_YEAR = 1980;
const END_YEAR = 2023;

const headers = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
};

function getDecade(year) {
  return Math.floor(year / 10) * 10;
}

// 괄호 및 특수문자 등 불필요한 꼬리표 1차 정제 로직
function cleanText(text) {
  return text.replace(/\(Live\)/gi, '')
             .replace(/\(Inst\.\)/gi, '')
             .replace(/\(MR\)/gi, '')
             .replace(/\(Special Edition\)/gi, '')
             .replace(/\s+/g, ' ')
             .trim();
}

async function scrapeMelonYearlyCharts() {
  const allSongs = [];
  const uniqueKeys = new Set();
  
  console.log(`🚀 Starting Melon Crawler: ${START_YEAR} to ${END_YEAR}`);

  for (let year = START_YEAR; year <= END_YEAR; year++) {
    const decade = getDecade(year);
    const url = `https://www.melon.com/chart/age/list.htm?idx=1&chartType=YE&chartMac=${decade}&chartYear=${year}`;
    
    try {
      const response = await axios.get(url, { headers });
      const $ = cheerio.load(response.data);
      
      let countForYear = 0;
      
      $('tbody tr').each((i, el) => {
        const titleRaw = $(el).find('.ellipsis.rank01 a').first().text();
        const artistRaw = $(el).find('.ellipsis.rank02 a').first().text();
        
        if (!titleRaw || !artistRaw) return;
        
        const title = cleanText(titleRaw);
        const artist = cleanText(artistRaw);
        
        // 멜론 차트 크롤링 시 장르와 성별은 명시되어 있지 않으므로 임시로 '가요/팝', '혼성' 등으로 설정 후 
        // 텍스트 패턴(아이돌 이름 등)으로 추후 보정 가능
        let genre = '발라드'; // Default
        let gender = '혼성';   // Default
        
        // 간단한 룰 기반 보정
        if (artist.match(/아이유|aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|이효리|백지영|보아|태연|윤하/i)) {
           gender = '여성';
        } else if (artist.match(/BTS|방탄소년단|세븐틴|EXO|BIGBANG|임영웅|조용필|성시경|박효신|SG워너비/i)) {
           gender = '남성';
        }

        if (artist.match(/aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|BTS|EXO|BIGBANG/i)) {
           genre = '댄스';
        } else if (artist.match(/임영웅|영탁|장윤정|송가인/i)) {
           genre = '트로트';
        } else if (artist.match(/버즈|DAY6|윤도현|잔나비|QWER/i)) {
           genre = '록/밴드';
        }

        // 중복 제거 키 (곡명_아티스트 소문자 공백제거)
        const key = `${title.toLowerCase().replace(/\s/g, '')}_${artist.toLowerCase().replace(/\s/g, '')}`;
        
        if (!uniqueKeys.has(key)) {
          uniqueKeys.add(key);
          allSongs.push({
            releaseYear: year, // 차트 진입(유행) 연도를 발매 연도로 대체
            releaseMonth: 1,   // 월 정보 부재로 1월 통일
            title: title,
            artist: artist,
            genre: genre,
            gender: gender
          });
          countForYear++;
        }
      });
      
      console.log(`✅ [${year}] Scraped ${countForYear} new unique songs (Total: ${allSongs.length})`);
      
      // Delay to avoid hitting rate limits
      await new Promise(r => setTimeout(r, 1000));
      
    } catch (error) {
      console.error(`❌ Error scraping year ${year}:`, error.message);
    }
  }
  
  console.log(`\n🎉 Scraping Completed! Total Unique Fact Songs: ${allSongs.length}`);
  
  // File Generation
  const fileContent = `// TJ Karaoke Melon Scraped Verified Songs Database (1980~2023)
// Total Unique Songs: ${allSongs.length}
// This file is auto-generated by melon_crawler.js

const SONG_DATABASE = ${JSON.stringify(allSongs, null, 2)};
`;
  
  fs.writeFileSync('C:/Users/minsu/.gemini/antigravity-ide/scratch/tj-random-song/songData.js', fileContent, 'utf8');
  console.log('💾 Successfully saved to songData.js');
}

scrapeMelonYearlyCharts();
