const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const fs = require('fs');

puppeteer.use(StealthPlugin());

const START_YEAR = 1980;
const END_YEAR = 2023;

function getDecade(year) {
  return Math.floor(year / 10) * 10;
}

function cleanText(text) {
  if (!text) return '';
  return text.replace(/\(Live\)/gi, '')
             .replace(/\(Inst\.\)/gi, '')
             .replace(/\(MR\)/gi, '')
             .replace(/\(Special Edition\)/gi, '')
             .replace(/\s+/g, ' ')
             .trim();
}

async function runScraper() {
  console.log('🚀 Starting Advanced Puppeteer Stealth Crawler (1980~2023)...');
  
  const browser = await puppeteer.launch({
    headless: "new",
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--window-size=1280,720']
  });
  
  const allSongs = [];
  const uniqueKeys = new Set();
  
  for (let year = START_YEAR; year <= END_YEAR; year++) {
    const decade = getDecade(year);
    const url = `https://www.melon.com/chart/age/index.htm?chartType=YE&chartMac=${decade}&chartYear=${year}`;
    
    console.log(`\n🌐 [${year}] Navigating to: ${url}`);
    
    // 매 연도마다 완전히 새로운 탭 생성! 캐시 완벽 차단.
    const page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 720 });
    await page.setCacheEnabled(false); // 캐시 비활성화
    
    try {
      await page.goto(url, { waitUntil: 'networkidle2', timeout: 20000 });
      
      try {
        await page.waitForSelector('.ellipsis.rank01 a', { timeout: 8000 });
      } catch (e) {
        console.log(`⚠️ Warning: Timeout waiting for selector on year ${year}.`);
      }

      const extractedSongs = await page.evaluate(() => {
        const rows = document.querySelectorAll('tbody tr');
        const data = [];
        
        rows.forEach(row => {
          const titleEl = row.querySelector('.ellipsis.rank01 a');
          const artistEl = row.querySelector('.ellipsis.rank02 a');
          
          if (titleEl && artistEl) {
            data.push({
              titleRaw: titleEl.innerText,
              artistRaw: artistEl.innerText
            });
          }
        });
        
        return data;
      });
      
      let countForYear = 0;
      
      for (const item of extractedSongs) {
        const title = cleanText(item.titleRaw);
        const artist = cleanText(item.artistRaw);
        
        let genre = '발라드'; 
        let gender = '혼성';   

        if (artist.match(/아이유|aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|이효리|백지영|보아|태연|에일리|레드벨벳/i)) {
           gender = '여성';
        } else if (artist.match(/BTS|방탄소년단|세븐틴|EXO|BIGBANG|임영웅|조용필|성시경|박효신|SG워너비|god|신승훈|김건모/i)) {
           gender = '남성';
        }

        if (artist.match(/aespa|IVE|NewJeans|BLACKPINK|소녀시대|TWICE|BTS|EXO|BIGBANG|H.O.T.|젝스키스|핑클|S.E.S.|코요태/i)) {
           genre = '댄스';
        } else if (artist.match(/임영웅|영탁|장윤정|송가인|주현미|김수희/i)) {
           genre = '트로트';
        } else if (artist.match(/버즈|DAY6|윤도현|잔나비|자우림|혁오|국카스텐/i)) {
           genre = '록/밴드';
        } else if (artist.match(/다이나믹 듀오|에픽하이|지코|비와이/i)) {
           genre = '힙합';
        }

        const key = `${title.toLowerCase().replace(/\s/g, '')}_${artist.toLowerCase().replace(/\s/g, '')}`;
        
        if (!uniqueKeys.has(key)) {
          uniqueKeys.add(key);
          allSongs.push({
            releaseYear: year,
            releaseMonth: 1, // 월간 차트가 아니므로 1월 고정
            title: title,
            artist: artist,
            genre: genre,
            gender: gender
          });
          countForYear++;
        }
      }
      
      console.log(`✅ [${year}] Scraped ${countForYear} unique songs. (Cumulative Total: ${allSongs.length})`);
      
    } catch (error) {
      console.error(`❌ Error scraping year ${year}:`, error.message);
    }
    
    // 추출 끝난 탭 닫기 (메모리 누수 및 세션 캐싱 방지)
    await page.close();
    
    // 멜론 차단 회피: 3~6초 무작위 지연
    const delay = Math.floor(Math.random() * 3000) + 3000;
    await new Promise(r => setTimeout(r, delay));
  }
  
  await browser.close();
  
  console.log(`\n🎉 Scraping Completed! Total Unique Fact Songs: ${allSongs.length}`);
  
  const fileContent = `// TJ Karaoke Melon Scraped Verified Songs Database (Advanced Puppeteer)
// Total Unique Songs: ${allSongs.length}
// Auto-generated by melon_puppeteer.js

const SONG_DATABASE = ${JSON.stringify(allSongs, null, 2)};
`;
  
  fs.writeFileSync('C:/Users/minsu/.gemini/antigravity-ide/scratch/tj-random-song/songData.js', fileContent, 'utf8');
  console.log('💾 Successfully saved to songData.js');
}

runScraper();
