// TJ Karaoke Genie Scraped Verified Songs Database (V10)
// Total Unique Songs: 343
// Auto-generated by genie_monthly_clicker.js

const SONG_DATABASE = [
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "Ditto",
    "artist": "NewJeans",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Hype Boy",
    "artist": "NewJeans",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE I AM",
    "artist": "IVE (아이브)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 사건의 지평선",
    "artist": "윤하 (YOUNHA)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE OMG",
    "artist": "NewJeans",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Kitsch",
    "artist": "IVE (아이브)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 퀸카 (Queencard)",
    "artist": "i-dle (아이들)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE After LIKE",
    "artist": "IVE (아이브)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 헤어지자 말해요",
    "artist": "박재정",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Attention",
    "artist": "NewJeans",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE LOVE DIVE",
    "artist": "IVE (아이브)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Spicy",
    "artist": "aespa",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE ANTIFRAGILE",
    "artist": "LE SSERAFIM (르세라핌)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 꽃",
    "artist": "지수 (JISOO)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 심 (心)",
    "artist": "DK (디셈버)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 사랑인가 봐",
    "artist": "멜로망스 (MeloMance)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Super Shy",
    "artist": "NewJeans",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE UNFORGIVEN (Feat. Nile Rodgers)",
    "artist": "LE SSERAFIM (르세라핌)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Teddy Bear",
    "artist": "STAYC (스테이씨)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 파이팅 해야지 (Feat. 이영지)",
    "artist": "부석순 (SEVENTEEN)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE ETA",
    "artist": "NewJeans",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "이브, 프시케 그리고 푸른 수염의 아내",
    "artist": "LE SSERAFIM (르세라핌)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 건물 사이에 피어난 장미",
    "artist": "H1-KEY (하이키)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 사랑은 늘 도망가",
    "artist": "임영웅",
    "genre": "트로트",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 너의 모든 순간",
    "artist": "성시경",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Seven (Feat. Latto) (Clean Ver.)",
    "artist": "정국",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 다정히 내 이름을 부르면",
    "artist": "경서예지 & 전건호",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Nxde",
    "artist": "i-dle (아이들)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 취중고백",
    "artist": "김민석 (멜로망스)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE TOMBOY",
    "artist": "i-dle (아이들)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 새삥 (Prod. by ZICO) (Feat. 호미들)",
    "artist": "지코 (ZICO)",
    "genre": "힙합",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 그때 그 순간 그대로 (그그그)",
    "artist": "WSG워너비 (가야G)",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Love Lee",
    "artist": "AKMU (악뮤)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Monologue",
    "artist": "테이 (Tei)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE CHRISTIAN",
    "artist": "Zior Park",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Shut Down",
    "artist": "BLACKPINK",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 해요 (2022)",
    "artist": "#안녕",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 그라데이션",
    "artist": "10CM",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "Pink Venom",
    "artist": "BLACKPINK",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 나의 X에게",
    "artist": "경서",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 주저하는 연인들을 위해",
    "artist": "잔나비",
    "genre": "록/밴드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "오르트구름",
    "artist": "윤하 (YOUNHA)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 내가 아니라도",
    "artist": "주호",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE ELEVEN",
    "artist": "IVE (아이브)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "후라이의 꿈",
    "artist": "AKMU (악뮤)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE NOT SORRY (Feat. pH-1) (Prod. by Slom)",
    "artist": "이영지",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 손오공",
    "artist": "세븐틴 (SEVENTEEN)",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Cookie",
    "artist": "NewJeans",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "우리들의 블루스",
    "artist": "임영웅",
    "genre": "트로트",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE VIBE (Feat. Jimin of BTS)",
    "artist": "태양",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 모든 날, 모든 순간 (Every day, Every Moment)",
    "artist": "폴킴",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 사막에서 꽃을 피우듯",
    "artist": "우디 (Woody)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 보고싶었어",
    "artist": "WSG워너비 (4FIRE)",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Dynamite",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Candy",
    "artist": "NCT DREAM",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 희재",
    "artist": "성시경",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 신호등",
    "artist": "이무진",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Cupid",
    "artist": "FIFTY FIFTY",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Smoke (Prod. by Dynamicduo & Padi)",
    "artist": "다이나믹 듀오 & 이영지",
    "genre": "힙합",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지",
    "artist": "AKMU (악뮤)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 정이라고 하자 (Feat. 10CM)",
    "artist": "BIG Naughty (서동현)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Say I Love You",
    "artist": "우디 (Woody)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE FEARLESS",
    "artist": "LE SSERAFIM (르세라핌)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 밤하늘의 별을 (2020)",
    "artist": "경서",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 물론",
    "artist": "허각",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 이제 나만 믿어요",
    "artist": "임영웅",
    "genre": "트로트",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 봄여름가을겨울 (Still Life)",
    "artist": "BIGBANG (빅뱅)",
    "genre": "댄스",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 사랑하기 싫어",
    "artist": "지아",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 예뻤어",
    "artist": "DAY6 (데이식스)",
    "genre": "록/밴드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE LOVE me",
    "artist": "BE'O (비오)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야",
    "artist": "장범준",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Rush Hour (Feat. j-hope of BTS)",
    "artist": "Crush",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 다시 만날 수 있을까",
    "artist": "임영웅",
    "genre": "트로트",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Fast Forward",
    "artist": "전소미",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE That That (Prod. & Feat. SUGA of BTS)",
    "artist": "싸이 (Psy)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Summer (Feat. BE'O (비오))",
    "artist": "Paul Blanco",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 자격지심 (Feat. ZICO)",
    "artist": "BE'O (비오)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 오늘도 빛나는 너에게 (To You My Light) (Feat.이라온)",
    "artist": "마크툽 (Maktub)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 사랑하지 않아서 그랬어",
    "artist": "임한별",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 딱 10CM만",
    "artist": "10CM & BIG Naughty (서동현)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE OHAYO MY NIGHT",
    "artist": "디핵 (D-Hack) & PATEKO",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 떠나보낼 준비해 둘걸 그랬어",
    "artist": "임한별",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "내 기쁨은 너가 벤틀리를 끄는 거야",
    "artist": "김승민",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Blueming",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Butter",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 한 페이지가 될 수 있게",
    "artist": "DAY6 (데이식스)",
    "genre": "록/밴드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 고백",
    "artist": "멜로망스 (MeloMance)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE INVU",
    "artist": "태연 (TAEYEON)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Next Level",
    "artist": "aespa",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "Celebrity",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 첫눈처럼 너에게 가겠다",
    "artist": "에일리 (Ailee)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "Love story",
    "artist": "볼빨간사춘기",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Weekend",
    "artist": "태연 (TAEYEON)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE strawberry moon",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 내 손을 잡아",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 봄날",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "무지개",
    "artist": "임영웅",
    "genre": "트로트",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 바라만 본다",
    "artist": "MSG워너비 (M.O.M)",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE Underwater",
    "artist": "권은비",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2023,
    "releaseMonth": 12,
    "title": "TITLE 우린 그렇게 사랑해서",
    "artist": "강민경 (다비치) & 잔나비 최정훈",
    "genre": "록/밴드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 회전목마 (Feat. Zion.T & 원슈타인) (Prod. by Slom)",
    "artist": "sokodomo",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE GANADARA (Feat. 아이유)",
    "artist": "박재범",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE Feel My Rhythm",
    "artist": "Red Velvet (레드벨벳)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 듣고 싶을까",
    "artist": "MSG워너비 (M.O.M)",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 리무진 (Feat. MINO) (Prod. by GRAY)",
    "artist": "BE'O (비오)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE Counting Stars (Feat. Beenzino)",
    "artist": "BE'O (비오)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 너를 생각해",
    "artist": "주시크 (Joosiq)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 언제나 사랑해",
    "artist": "케이시 (Kassy)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 호랑수월가",
    "artist": "탑현",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 문득",
    "artist": "BE'O (비오)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "드라마",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 라일락",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 서랍",
    "artist": "10CM",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "MY BAG",
    "artist": "i-dle (아이들)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 눈이 오잖아 (Feat. 헤이즈)",
    "artist": "이무진",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 만남은 쉽고 이별은 어려워 (Feat. Leellamarz) (Prod. by TOIL)",
    "artist": "베이식 (Basick)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 헤픈 우연",
    "artist": "헤이즈 (Heize)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 찰나가 영원이 될 때 (The Eternal Moment)",
    "artist": "마크툽 (Maktub)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE POP!",
    "artist": "나연 (TWICE)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 어제처럼",
    "artist": "폴킴",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 겨울잠",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 낙하 (With 아이유)",
    "artist": "AKMU (악뮤)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE Savage",
    "artist": "aespa",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE Permission to Dance",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE SMILEY (Feat. BIBI)",
    "artist": "YENA (최예나)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE Step Back",
    "artist": "GOT the beat",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 사이렌 Remix (Feat. UNEDUCATED KID & Paul Blanco)",
    "artist": "호미들",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 오래된 노래",
    "artist": "Standing Egg (스탠딩 에그)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 스물다섯, 스물하나",
    "artist": "자우림",
    "genre": "록/밴드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 롤린 (Rollin')",
    "artist": "브레이브걸스 (Brave girls)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 에잇 (Prod. & Feat. SUGA of BTS)",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE ZOOM",
    "artist": "제시 (Jessi)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE FOREVER 1",
    "artist": "소녀시대 (GIRLS' GENERATION)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE SNEAKERS",
    "artist": "ITZY (있지)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 아로하",
    "artist": "조정석",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 비와 당신",
    "artist": "이무진",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 밝게 빛나는 별이 되어 비춰줄게",
    "artist": "송이한",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE METEOR",
    "artist": "창모 (CHANGMO)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 비가 오는 날엔 (2021)",
    "artist": "헤이즈 (Heize)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 팡파레",
    "artist": "다비치",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 작은 것들을 위한 시 (Boy With Luv) (Feat. Halsey)",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 너의 번호를 누르고 (Prod. by 영화처럼)",
    "artist": "#안녕",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 우리가 헤어져야 했던 이유",
    "artist": "비비 (BIBI)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 추억은 만남보다 이별에 남아",
    "artist": "정동하",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 흰눈",
    "artist": "먼데이 키즈",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE Dun Dun Dance",
    "artist": "오마이걸 (OH MY GIRL)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE Timeless",
    "artist": "SG워너비",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "도깨비불 (Illusion)",
    "artist": "aespa",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2022,
    "releaseMonth": 12,
    "title": "TITLE 늦은 밤 너의 집 앞 골목길에서",
    "artist": "노을",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE VVS (Feat. JUSTHIS) (Prod. by GroovyRoom)",
    "artist": "미란이 (MIRANI) & 먼치맨 (MUNCHMAN) & Khundi Panda & 머쉬베놈 (MUSHVENOM)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 운전만해 (We Ride)",
    "artist": "브레이브걸스 (Brave girls)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 잠이 오질 않네요",
    "artist": "장범준",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE Lovesick Girls",
    "artist": "BLACKPINK",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 우린 어쩌다 헤어진 걸까",
    "artist": "허각",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 취기를 빌려 (취향저격 그녀 X 산들)",
    "artist": "산들",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE Life Goes On",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE LOVE DAY (2021) (바른연애 길잡이 X 양요섭, 정은지)",
    "artist": "양요섭 & 정은지",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 이 밤을 빌려 말해요 (바른연애 길잡이 X 10CM)",
    "artist": "10CM",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 힘든 건 사랑이 아니다",
    "artist": "임창정",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "Dolphin",
    "artist": "오마이걸 (OH MY GIRL)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 상상더하기",
    "artist": "라붐 (LABOUM)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE Coin",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 치맛바람 (Chi Mat Ba Ram)",
    "artist": "브레이브걸스 (Brave girls)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 내 마음이 움찔했던 순간 (취향저격 그녀 X 규현)",
    "artist": "규현 (KYUHYUN)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 그날에 나는 맘이 편했을까",
    "artist": "이예준",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE On The Ground",
    "artist": "로제 (ROSÉ)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 나랑 같이 걸을래 (바른연애 길잡이 X 적재)",
    "artist": "적재",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE ASAP",
    "artist": "STAYC (스테이씨)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 마음을 드려요",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 라라라",
    "artist": "SG워너비",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 좋아좋아",
    "artist": "조정석",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "어푸 (Ah puh)",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 내일이 오면 (Feat. 기리보이 & BIG Naughty (서동현))",
    "artist": "릴보이 (lIlBOI)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 안녕",
    "artist": "폴킴",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE Alcohol-Free",
    "artist": "TWICE (트와이스)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 어떻게 지내 (Prod. by VAN.C)",
    "artist": "오반 (OVAN)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 고백 (바른연애 길잡이 X 허각)",
    "artist": "허각",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 시작",
    "artist": "가호 (Gaho)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 안녕 (Hello)",
    "artist": "조이 (JOY)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 밤하늘의 저 별처럼",
    "artist": "헤이즈 (Heize) & 펀치 (Punch)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 살짝 설렜어 (Nonstop)",
    "artist": "오마이걸 (OH MY GIRL)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 사실 나는 (Feat. 전건호)",
    "artist": "경서예지",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 멜로디",
    "artist": "ASH ISLAND",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 밤편지",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 하루만 더",
    "artist": "빅마마 (Big Mama)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 혼술하고 싶은 밤",
    "artist": "벤",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 사랑하게 될 줄 알았어",
    "artist": "전미도",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE How You Like That",
    "artist": "BLACKPINK",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 상상더하기",
    "artist": "MSG워너비",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE What Do I Call You",
    "artist": "태연 (TAEYEON)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 너를 만나",
    "artist": "폴킴",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 비 오는 날 듣기 좋은 노래 (Feat. Colde)",
    "artist": "에픽하이 (EPIK HIGH)",
    "genre": "힙합",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE Love poem",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 술 한잔 해요",
    "artist": "경서 (경서예지) & MJ (써니사이드)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 추적이는 여름 비가 되어",
    "artist": "장범준",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE HERO",
    "artist": "임영웅",
    "genre": "트로트",
    "gender": "남성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE When We Disco (Duet With 선미)",
    "artist": "박진영",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 그냥 안아달란 말야",
    "artist": "다비치",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "Way Back Home",
    "artist": "숀 (SHAUN)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE Your Lights",
    "artist": "이수 (엠씨더맥스)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 나를 아는 사람",
    "artist": "MSG워너비 (정상동기)",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 요즘",
    "artist": "양다일",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 좋은 사람 있으면 소개시켜줘",
    "artist": "조이 (JOY)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 아무노래",
    "artist": "지코 (ZICO)",
    "genre": "힙합",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE Downtown Baby",
    "artist": "블루 (BLOO)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 딩가딩가 (Dingga)",
    "artist": "마마무(Mamamoo)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 노래방에서",
    "artist": "장범준",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 사계 (Four Seasons)",
    "artist": "태연 (TAEYEON)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE 내사람 : Partner For Life",
    "artist": "SG워너비",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2021,
    "releaseMonth": 12,
    "title": "TITLE ON AIR (Feat. 로꼬 & 박재범 & GRAY)",
    "artist": "릴보이 (lIlBOI)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE Psycho",
    "artist": "Red Velvet (레드벨벳)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE HIP",
    "artist": "마마무(Mamamoo)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE Square (2017)",
    "artist": "백예린 (Yerin Baek)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 마리아 (Maria)",
    "artist": "화사 (Hwa Sa)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 아마두 (Feat. 우원재 & 김효은 & 넉살 & Huckleberry P)",
    "artist": "염따 & 딥플로우 & 팔로알토 (Paloalto) & The Quiett & 사이먼 도미닉",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 다시 여기 바닷가",
    "artist": "싹쓰리 (유두래곤 & 린다G & 비룡)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 처음처럼",
    "artist": "엠씨더맥스 (M.C the MAX)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 조금 취했어 (Prod. by 2soo)",
    "artist": "임재현",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 사랑이란 멜로는 없어",
    "artist": "전상근",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 시든 꽃에 물을 주듯",
    "artist": "HYNN (박혜원)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE ON",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 나의 오랜 연인에게",
    "artist": "다비치",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 돌덩이",
    "artist": "하현우 (국카스텐)",
    "genre": "록/밴드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE WANNABE",
    "artist": "ITZY (있지)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 다시 난, 여기",
    "artist": "백예린 (Yerin Baek)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 사랑에 연습이 있었다면 (Prod. by 2soo)",
    "artist": "임재현",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 포장마차",
    "artist": "황인욱",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 사랑이 식었다고 말해도 돼",
    "artist": "먼데이 키즈",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 다시 만날까 봐",
    "artist": "V.O.S",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 기억해줘요 내 모든 날과 그때를",
    "artist": "거미 (GUMMY)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 우리 왜 헤어져야 해",
    "artist": "신예영",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 나비와 고양이 (Feat. 백현 (BAEKHYUN))",
    "artist": "볼빨간사춘기",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 니 소식",
    "artist": "송하예",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 다시는 사랑하지 않고, 이별에 아파하기 싫어",
    "artist": "백지영",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 덤더럼 (Dumhdurum)",
    "artist": "Apink (에이핑크)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 그때 그 아인",
    "artist": "김필",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 눈누난나 (NUNU NANA)",
    "artist": "제시 (Jessi)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE Summer Hate (Feat. 비)",
    "artist": "지코 (ZICO)",
    "genre": "힙합",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 새 사랑",
    "artist": "송하예",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 반만",
    "artist": "진민호",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 헤어진 우리가 지켜야 할 것들",
    "artist": "김나영 & 양다일",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 그대라는 시",
    "artist": "태연 (TAEYEON)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 있어줘요",
    "artist": "장덕철",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE FIESTA",
    "artist": "IZ*ONE (아이즈원)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 내 눈물 모아",
    "artist": "휘인 (Whee In)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "빌었어",
    "artist": "창모 (CHANGMO)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 그때가 좋았어",
    "artist": "케이시 (Kassy)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 홀로",
    "artist": "이하이",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 워커홀릭",
    "artist": "볼빨간사춘기",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 비",
    "artist": "폴킴",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 문득",
    "artist": "노을",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 너에게 못했던 내 마지막 말은",
    "artist": "다비치",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE MORE & MORE",
    "artist": "TWICE (트와이스)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 인기 (Feat. 송가인 & 챈슬러)",
    "artist": "MC몽",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 술이 문제야",
    "artist": "장혜진 & 윤민수(바이브)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE Into the I-LAND",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 먹구름",
    "artist": "윤하 (YOUNHA)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "시간의 바깥",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 보라빛 밤 (pporappippam)",
    "artist": "선미",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 화려하지 않은 고백",
    "artist": "규현 (KYUHYUN)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 여름 안에서 (Feat. 황광희)",
    "artist": "싹쓰리 (유두래곤 & 린다G & 비룡)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 너에게 난, 나에게 넌",
    "artist": "미도와 파라솔",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 어떤 날엔",
    "artist": "김재환",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 십이월 이십오일의 고백",
    "artist": "정승환",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 잘 지내고 있는지 궁금해",
    "artist": "V.O.S",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 그 여름을 틀어줘",
    "artist": "싹쓰리 (유두래곤 & 린다G & 비룡)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 옥탑방 (Rooftop)",
    "artist": "엔플라잉 (N.Flying)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE PLAY (Feat. 창모)",
    "artist": "청하",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 불티 (Spark)",
    "artist": "태연 (TAEYEON)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "Black Swan",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 여행",
    "artist": "볼빨간사춘기",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 마음이 말하는 행복 (Happiness) (Feat.이라온)",
    "artist": "마크툽 (Maktub)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 이 번호로 전화해줘",
    "artist": "바이브",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2020,
    "releaseMonth": 12,
    "title": "TITLE 둘만의 세상으로 가",
    "artist": "Crush",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 넘쳐흘러",
    "artist": "엠씨더맥스 (M.C the MAX)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 벌써 12시",
    "artist": "청하",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 달라달라",
    "artist": "ITZY (있지)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 180도",
    "artist": "벤",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 신용재",
    "artist": "하은 (포맨)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 이 노래가 클럽에서 나온다면",
    "artist": "우디 (Woody)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 나만, 봄",
    "artist": "볼빨간사춘기",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE SOLO",
    "artist": "제니 (JENNIE)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 내 생에 아름다운",
    "artist": "케이윌 (K.Will)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE YES or YES",
    "artist": "TWICE (트와이스)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 아낙네",
    "artist": "MINO (송민호)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 삐삐",
    "artist": "아이유 (IU)",
    "genre": "발라드",
    "gender": "여성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE FANCY",
    "artist": "TWICE (트와이스)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "사계 (하루살이)",
    "artist": "엠씨더맥스 (M.C the MAX)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 솔직하게 말해서 나",
    "artist": "김나영",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 너도 그냥 날 놓아주면 돼",
    "artist": "윤건",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 헤어져줘서 고마워",
    "artist": "벤",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 당신과는 천천히",
    "artist": "장범준",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 고백",
    "artist": "양다일",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 가을 타나 봐",
    "artist": "바이브",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 멍청이 (twit)",
    "artist": "화사 (Hwa Sa)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Kill This Love",
    "artist": "BLACKPINK",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 열애중",
    "artist": "벤",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 이별하러 가는 길",
    "artist": "임한별",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 띵 (Prod. by 기리보이)",
    "artist": "Jvcki Wai & 양홍원 & Osshun Gum & 한요한",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 지나오다",
    "artist": "닐로 (Nilo)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 별 보러 갈래?",
    "artist": "볼빨간사춘기",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 사월이 지나면 우리 헤어져요 (Beautiful goodbye)",
    "artist": "첸 (CHEN)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Snapping",
    "artist": "청하",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE IDOL",
    "artist": "방탄소년단",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 미안해",
    "artist": "양다일",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 그건 아마 우리의 잘못은 아닐 거야",
    "artist": "백예린 (Yerin Baek)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 흔한 이별",
    "artist": "허각",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 하루도 그대를 사랑하지 않은 적이 없었다",
    "artist": "임창정",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Goodbye",
    "artist": "박효신",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 신청곡 (Feat. SUGA of BTS)",
    "artist": "이소라",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 취하고 싶다 (Prod. by 전태익)",
    "artist": "황인욱",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE MILLIONS",
    "artist": "WINNER",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 고고베베 (gogobebe)",
    "artist": "마마무(Mamamoo)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Dance The Night Away",
    "artist": "TWICE (트와이스)",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Good Day (Feat. 팔로알토) (Prod. by 코드 쿤스트)",
    "artist": "pH-1 & 키드밀리 (Kid Milli) & 루피 (Loopy) & 코드 쿤스트 (CODE KUNST)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 잘 지내요",
    "artist": "정승환",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 그날처럼",
    "artist": "장덕철",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 선물",
    "artist": "멜로망스 (MeloMance)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 너는 어땠을까",
    "artist": "노을",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 첫눈에",
    "artist": "헤이즈 (Heize)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 진심이 담긴 노래 (True Song)",
    "artist": "케이시 (Kassy)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 대충 입고 나와",
    "artist": "우디 (Woody)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 초록빛",
    "artist": "폴킴",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "길 (Song by 아이유 & 헨리 & 조현아 & 양다일)",
    "artist": "지오디 (god)",
    "genre": "발라드",
    "gender": "남성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 봄 (Feat. 산다라박)",
    "artist": "박봄 (Park Bom)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 가을밤 떠난 너",
    "artist": "케이시 (Kassy)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 술이 달다 (Feat. Crush)",
    "artist": "에픽하이 (EPIK HIGH)",
    "genre": "힙합",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 뚜두뚜두 (DDU-DU DDU-DU)",
    "artist": "BLACKPINK",
    "genre": "댄스",
    "gender": "여성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 인사",
    "artist": "멜로망스 (MeloMance)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Love Shot",
    "artist": "EXO",
    "genre": "댄스",
    "gender": "남성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 습관 (Bad Habits)",
    "artist": "숀 (SHAUN)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE flex (Prod. by 기리보이)",
    "artist": "기리보이 & 키드밀리 (Kid Milli) & NO:EL & 스윙스",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 가을 안부",
    "artist": "먼데이 키즈",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Roller Coaster",
    "artist": "청하",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 내 목소리 들리니",
    "artist": "벤",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE Done For Me",
    "artist": "펀치 (Punch)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 비가 내리는 날에는",
    "artist": "윤하 (YOUNHA)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE ICY",
    "artist": "ITZY (있지)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 누구 없소 (NO ONE) (Feat. B.I of iKON)",
    "artist": "이하이",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 19금 BAND",
    "artist": "창모 & Hash Swan & ASH ISLAND & 김효은",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 오늘 밤에",
    "artist": "홍진영",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "You",
    "artist": "멜로망스 (MeloMance)",
    "genre": "발라드",
    "gender": "혼성"
  },
  {
    "releaseYear": 2019,
    "releaseMonth": 12,
    "title": "TITLE 나의 어깨에 기대어요",
    "artist": "10CM",
    "genre": "발라드",
    "gender": "혼성"
  }
];
