const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');

const URLS = [
  'https://ko.wikipedia.org/wiki/%EB%AE%A4%EC%A7%81%EB%B1%85%ED%81%AC_1%EC%9C%84_%EA%B3%A1_%EB%AA%A9%EB%A1%9D', // 뮤직뱅크 1위 곡 목록
  'https://ko.wikipedia.org/wiki/%EC%9D%B8%EA%B8%B0%EA%B0%80%EC%9A%94_1%EC%9C%84_%EA%B3%A1_%EB%AA%A9%EB%A1%9D', // 인기가요 1위 곡 목록
  'https://ko.wikipedia.org/wiki/%EC%87%BC!_%EC%9D%8C%EC%95%85%EC%A4%91%EC%8B%AC_1%EC%9C%84_%EA%B3%A1_%EB%AA%A9%EB%A1%9D' // 쇼 음악중심 1위 곡 목록
];

function cleanText(text) {
  if (!text) return '';
  // 위키백과 각주 제거 [1], [2]
  return text.replace(/\[\d+\]/g, '')
             .replace(/"/g, '')
             .replace(/'/g, '')
             .trim();
}

async function scrapeWiki() {
  const allSongs = [];
  const uniqueKeys = new Set();
  
  console.log(`🚀 Starting Wikipedia K-Pop Chart Crawler`);

  for (const url of URLS) {
    try {
      const response = await axios.get(url);
      const $ = cheerio.load(response.data);
      
      let count = 0;
      
      // 위키백과 표(wikitable) 순회
      $('table.wikitable tbody tr').each((i, el) => {
        // 테이블 형식에 따라 다를 수 있으나, 일반적으로:
        // th, td 등에서 날짜, 곡명, 가수명이 들어있음
        const tds = $(el).find('td');
        if (tds.length >= 3) {
          // 뮤직뱅크/인기가요의 전형적인 테이블 형식 (날짜 | 곡명 | 아티스트)
          // 텍스트를 모두 추출하여 길이가 긴 문자열을 곡명이나 가수로 휴리스틱 파싱
          
          let title = '';
          let artist = '';
          
          // 보통 인덱스 1이 곡명, 2가 가수 (예외 존재 가능)
          const tdTexts = [];
          $(el).find('td').each((j, tdEl) => {
            tdTexts.push(cleanText($(tdEl).text()));
          });

          // 아주 단순화된 위키 테이블 추출 규칙
          // 보통 곡명에는 "표시가 있을 수 있음. 텍스트 길이가 유효한 값을 찾음.
          // 여기서는 tdTexts 중 인덱스 1과 2를 사용 (날짜 표기가 맨 앞일 경우)
          if (tdTexts[0] && tdTexts[0].includes('월')) {
             title = tdTexts[1];
             artist = tdTexts[2];
          } else if (tdTexts[1] && tdTexts[1].includes('월')) {
             title = tdTexts[2];
             artist = tdTexts[3];
          } else {
             title = tdTexts[1] || '';
             artist = tdTexts[2] || '';
          }

          if (title && artist && title.length > 1 && artist.length > 1) {
            
            // 장르/성별은 기본값 세팅 후, 자주 등장하는 아티스트 보정
            let gender = '혼성';
            let genre = '댄스'; // 1위 곡은 댄스가 압도적으로 많음

            if (artist.match(/소녀시대|트와이스|아이유|블랙핑크|레드벨벳|에스파|아이브|뉴진스|마마무|여자친구|에이핑크/i)) {
               gender = '여성';
            } else if (artist.match(/방탄소년단|엑소|빅뱅|동방신기|슈퍼주니어|샤이니|세븐틴|스트레이 키즈|투모로우바이투게더/i)) {
               gender = '남성';
            }

            if (artist.match(/임영웅|장윤정/i)) genre = '트로트';
            else if (artist.match(/발라드|김동률|성시경|박효신|SG워너비/i)) genre = '발라드';

            // 키 생성
            const key = `${title.toLowerCase().replace(/\s/g, '')}_${artist.toLowerCase().replace(/\s/g, '')}`;
            
            if (!uniqueKeys.has(key)) {
              uniqueKeys.add(key);
              allSongs.push({
                releaseYear: 2010, // 임시 연도 
                releaseMonth: 1, 
                title: title,
                artist: artist,
                genre: genre,
                gender: gender
              });
              count++;
            }
          }
        }
      });
      
      console.log(`✅ Scraped ${count} new unique songs from URL`);
      
    } catch (error) {
      console.error(`❌ Error scraping URL:`, error.message);
    }
  }
  
  console.log(`\n🎉 Scraping Completed! Total Unique Fact Songs: ${allSongs.length}`);
  
  // File Generation
  const fileContent = `// TJ Karaoke Wiki Scraped Verified Songs Database
// Total Unique Songs: ${allSongs.length}
// Auto-generated by wiki_crawler.js

const SONG_DATABASE = ${JSON.stringify(allSongs, null, 2)};
`;
  
  fs.writeFileSync('C:/Users/minsu/.gemini/antigravity-ide/scratch/tj-random-song/songData.js', fileContent, 'utf8');
  console.log('💾 Successfully saved to songData.js');
}

scrapeWiki();
